parameters:
    # path from project root
    swagger_bundle.swagger_file: Resources/docs/swagger.yaml

    # swagger mock api toggle
    swagger_bundle.mock_api: true

    # service classes
    swagger_bundle.factory.swagger.class:   Epfremme\Swagger\Factory\SwaggerFactory
    swagger_bundle.provider.swagger.class:  Epfremme\SwaggerBundle\Provider\SwaggerProvider
    swagger_bundle.provider.schema.class:   Epfremme\SwaggerBundle\Provider\SchemaProvider
    swagger_bundle.listener.mock_api.class: Epfremme\SwaggerBundle\EventListener\MockApiListener

services:

    swagger_bundle.factory.swagger:
        class: %swagger_bundle.factory.swagger.class%

    swagger_bundle.provider.swagger:
        class: %swagger_bundle.provider.swagger.class%
        arguments:
          - "@kernel"
          - "@swagger_bundle.factory.swagger"
          - %swagger_bundle.swagger_file%

    swagger_bundle.provider.schema:
        class: %swagger_bundle.provider.schema.class%
        arguments:
          - "@swagger_bundle.provider.swagger"

    kernel.listener.mock_api_listener:
        class: %swagger_bundle.listener.mock_api.class%
        arguments:
          - "@kernel"
          - %swagger_bundle.swagger_file%
          - %swagger_bundle.mock_api%
        tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
