parameters:
    # path from project root
    swagger_bundle.swagger_file: Resources/docs/swagger.yaml

    # service classes
    swagger_bunele.factory.swagger.class:  Nerdery\Swagger\Factory\SwaggerFactory
    swagger_bundle.provider.swagger.class: Nerdery\SwaggerBundle\Provider\SwaggerProvider
    swagger_bundle.provider.schema.class: Nerdery\SwaggerBundle\Provider\SchemaProvider

services:

    swagger_bundle.factory.swagger:
        class: %swagger_bunele.factory.swagger.class%

    swagger_bundle.provider.swagger:
        class: %swagger_bundle.provider.swagger.class%
        arguments:
          - @kernel
          - @swagger_bundle.factory.swagger
          - %swagger_bundle.swagger_file%

    swagger_bundle.provider.schema:
        class: %swagger_bundle.provider.schema.class%
        arguments:
          - @swagger_bundle.provider.swagger